### ISSUE TITLE
运行提示这个错误

### ISSUE THREAD

**Issue by vipxiaoma** [MetaInsight7/MaskFaceTool#1]
![image](https://github.com/MetaInsight7/MaskFaceTool/assets/12783488/4c9d8622-92a8-4703-a8b6-93b5f3a5ff6a)

请问一下，这个需要怎么解决，谢谢！

**Comment by MetaInsight7** [comment]
you can follow this https://github.com/MetaInsight7/MaskFaceTool/tree/main/utils/cython

**Comment by MetaInsight7** [comment]
使用cython加速，需要先在linux系统下编译文件，如果不是linux系统则无法使用cython加速
step1:进入到utils/cython目录下
step2:执行python setup.py build_ext -i 生成文件
step3:将生成.so文件重命名为render.so

**Comment by vipxiaoma** [comment]
![image](https://github.com/MetaInsight7/MaskFaceTool/assets/12783488/6d4033dc-c5f6-4a6b-9ff2-1dba6dc39da4)
非常感谢，现在运行提示这个错误

**Comment by vipxiaoma** [comment]
![image](https://github.com/MetaInsight7/MaskFaceTool/assets/12783488/d0c84d7e-63ee-44c0-a095-6d215e3767cc)
这是我的依赖包版本

**Comment by vipxiaoma** [comment]
问题已解决，需要调整代码

face_mask, new_image = render_cy(np.ascontiguousarray(vertices.T), np.ascontiguousarray(new_colors.T), np.ascontiguousarray(self.prn.triangles.T.astype(np.int64)), h, w)

改为

face_mask, new_image = render_cy(np.ascontiguousarray(vertices.T), np.ascontiguousarray(new_colors.T), np.ascontiguousarray(self.prn.triangles.T.astype(np.int32)), h, w)

**Comment by MetaInsight7** [comment]
感谢反馈！
